### ISSUE TITLE
Page 2: Unclear introduction, COBOL example might be unfitting in the way it is phrased

### ISSUE THREAD

**Issue by rcschrg** [NFDI4Energy/EFZN_rdm#11]
- The introduction of the COBOL problem is only half the truth. The problem with the COBOL story is not even the language itself, but the platform that goes along with it, and that is a bit out of time (cue mainframe, zOS, DB2 zOS), and that basically brings the problem that you A. can't get people who know the platform including COBOL, and B. Today's development patterns are hardly transferable to the mainframe (e.g. try to bring Docker-based DevOps pipelines to the host, there are Unixoid subsystems now, but they are treated quite stepmotherly), 
C. you are very dependent on the mainframe vendor (IBM). From personal experience I would say mainframe experience is probably more important than the COBOL language itself (which is really easy to learn, but is definitely a slow language to develop).

- The comparison itself makes sense somewhere, but could be better worded:
The analogy is with respect to the largely proprietary system COBOL on the host (mainframe) vs. data with proprietary software/data formats. Thus both have an accessibility problem, hence both are difficult to communicate.

**Comment by SagerJ** [comment]
I had similar issues with the COBOL motivation pitch so I will comment here instead of adding a new issue. The chain of reasoning as of now goes:

"Covid 19 happened" => "A government program failed because some old systems failed" => "systems failed (presumably) because of lack of COBOL devs to maintain and/or fix the issue" => "COBOL devs are lacking because the language is old and barely taught anymore" => "???????" => "RDM would have helped this issue".


The last step of this chain is not obvious to me.

**Comment by JuliaHeiken** [comment]
To do @sferenz : Replace example.

**Comment by sferenz** [comment]
Already in #20, therefore, I close this issue.
